### ISSUE TITLE
Noetic(Python3): struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by reinzor** [iron-ox/fadecandy_ros#12]
```
fadecandy_driver/src/fadecandy_driver/fadecandy_driver.py", line 67, in make_video_usb_packets
    packet = VIDEO_PACKET_STRUCT.pack(control, *color_bytes)
struct.error: required argument is not an integer
```

**Comment by wongkaiweng** [comment]
#13 is merged and should have resolved the issue.

**Comment by reinzor** [comment]
Can we make a patch release :)?

**Comment by wongkaiweng** [comment]
Let me take a look at that.

**Comment by wongkaiweng** [comment]
Ok finally. Here are the two PRs going into rosdistro: 
Melodic: https://github.com/ros/rosdistro/pull/27232
Noetic: https://github.com/ros/rosdistro/pull/27233

**Comment by wongkaiweng** [comment]
Both of them are merged. Good to go.
