### ISSUE TITLE
Refactor to C++

### ISSUE THREAD

**Issue by reinzor** [iron-ox/fadecandy_ros#14]
Hi,

We are thinking about refactoring this driver to C++ since it is eating quite some resources when having a lot of leds on sending resources on high rates. What do you think? Would you be open for a PR?

**Comment by wongkaiweng** [comment]
@reinzor Yes, we would be open for a PR. Thanks in advance for refactoring the driver.

**Comment by reinzor** [comment]
FYI, we are in the process of refactoring the driver; you can expect a PR soon :)

**Comment by jadhm** [comment]
Pull request is sent #20

**Comment by reinzor** [comment]
Resolved by #20
