### ISSUE TITLE
ROS release

### ISSUE THREAD

**Issue by reinzor** [iron-ox/fadecandy_ros#21]
Hi,

I'm trying to `bloom-release` a the `0.2.0` version of this package but I do not have permissions to the https://github.com/iron-ox/fadecandy_ros-release repository . Could you help me with this? BTW, should we update the maintainers / authors in the `package.xml`. What do you think.

Thanks!

**Comment by pixelparts** [comment]
I've granted you write access to the repo

**Comment by reinzor** [comment]
@pixelparts Thanks! Should I update the maintainer in the `package.xml`? Currently it is set to:

```
<maintainer email="jon.binney@ironox.com">Jon Binney</maintainer>
```

Is this still valid? Should I add my name to it or replace it? Or someone else's name? Should we add an `author` tag?

**Comment by pixelparts** [comment]
Please remove Jon and instead add @venkisagunner93 and yourself as maintainers.

**Comment by reinzor** [comment]
Updated in https://github.com/iron-ox/fadecandy_ros/commit/ed452eddc4fbc9af5a38d0abfa34a051f8e7decb

**Comment by reinzor** [comment]
- Melodic release: https://github.com/ros/rosdistro/pull/29216
- Noetic release: https://github.com/ros/rosdistro/pull/29217
