### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by reinzor** [iron-ox/fadecandy_ros#4]
Thanks for making this package publicly available. What is the status of this package? Is there any plan for releasing this package?

We would like to continue our development based on this package and do the following:
- Split into `fadecandy_driver`, `fadecandy_msgs`
- Add serial number diagnostics
- Pep8 compliant styling according to the ros python guidelines

Would you be open to accept pull requests for this?

Thanks!

**Comment by reinzor** [comment]
ping @jonbinney

**Comment by jonbinney** [comment]
@reinzor thanks for pinging - i wasn't watching this package so i wasn't getting notifications :-(

I'd be happy to accept pull requests for those changes! I can also release this repo. We use this code all the time, but have so far been using it from source.

**Comment by jonbinney** [comment]
@reinzor Unrelated note: we found that the charge pump chip on the fadecandy board doesn't always provide a reliable 5 volts, and had to wire in an external 5 volt supply to get them to work reliably.

**Comment by reinzor** [comment]
Refactor covered in https://github.com/iron-ox/fadecandy_ros/pull/5
