### ISSUE TITLE
Debian releases

### ISSUE THREAD

**Issue by reinzor** [iron-ox/fadecandy_ros#6]
Could you do a release for:

- Melodic
- Noetic (not sure whether everything is py3 compatible)

**Comment by jonbinney** [comment]
Sure! I should get to this in the next couple days.

**Comment by jonbinney** [comment]
Released into melodic: https://github.com/ros/rosdistro/pull/25165

**Comment by jonbinney** [comment]
I'm going to wait until the melodic release gets merged before doing the noetic release, so that bloom will autofill the noetic fields for me....

**Comment by jonbinney** [comment]
Released into noetic:  https://github.com/ros/rosdistro/pull/25171

**Comment by jonbinney** [comment]
So close! Have to add a rosdep rule for python3-usb first: https://github.com/ros/rosdistro/pull/25173

**Comment by jonbinney** [comment]
Rosdep rule created, and new release for this repo created: https://github.com/ros/rosdistro/pull/25298
